INSERT INTO CUSTOMER VALUES (1,'Big News Media Corp',1);
INSERT INTO CUSTOMER VALUES (2,'Online Mega Store',1);
INSERT INTO CUSTOMER VALUES	(3,'Nachoroo Delivery',0);
INSERT INTO CUSTOMER VALUES (4,'Euro Telecom Group',1);

INSERT INTO IP_BLACKLIST VALUES ('0');
INSERT INTO IP_BLACKLIST VALUES ('2130706433');
INSERT INTO IP_BLACKLIST VALUES ('4294967295');

INSERT INTO UA_BLACKLIST VALUES ('A6-Indexer');
INSERT INTO UA_BLACKLIST VALUES ('Googlebot-News');
INSERT INTO UA_BLACKLIST VALUES ('Googlebot');

